### ISSUE TITLE
[Suggestion] Enhance the AOP functions by Attributes not only relying on HttpPipelineModule

### ISSUE THREAD

**Issue by MaleDong** [aspnet/SignalR-Server#102]
Since SignalR 1.X we have HubPipelineModlue——which lets us inject and intercope with methods by "OnBeforeComing" or "OnAfterComing" easily. However this seems a little "dull" if we have many different kinds requests, and you have to define different kinds of Modules and inject them by calling the releated extended method at Application_Start for the global.asax.

In my mind, why don't we do something like MVC5,MVC6——I mean in my mind, SignalR 3 should be something surrounding with Attributes:

1) Open some public basic interfaces such as IAuthorizeHubConnection……

2) Extend these interfaces with abstract classes as the MOST basic functions, allows users to inherit from them directly to complete their own tasks. However these abstract classes are "Attributes". This means your "Attribute class" can be used both like a common class, and an attribute for AOP as well.

3) Your HttpModulePipeLine should have an extended method (something called "RegisterCustomerInjection"), this function is an overload one that can accept these interfaces as its own parameters：

3.1) If you register them in the Global.asax, this will affect on every methods defined in the SignalR. 
3.2) If you apply the attributes on any SignalR class, it will affect on one class and all of its methods.
3.3) If you apply the attributes on any SignalR's class's one method, only the method will be affected.
3.4) Notice you should create a global attribute called "NonInjectionAttribute", this attribute can be used only on method, which means the method won'be affected by attributes on its class, or even you've registered at Global.asax, the method won't be affected, either.

【Sample Registrations on classes/methods】
 [CustomerAttributeForClass]
 public class XXX : Hub<YYY>
{
    [CustomerAttributeForMethod]
    public void Fun(){……}
    [NonInjection]
    public void Fun2(){……}
}

At Global.asax:
SomeSignalRClass.RegisterCustomerInjection(GlobalCustomerAttribute);

So the order is:
1) GlobalCustomerAttribute
2) CustomerAttributeForClass
3) CustomerAttributeForMethod

And what's more——
Notice that Since "CustomerAttributeForClass" is registered for the whole class, so all the methods in it will be affected, and since "Fun2" has its own "NonInjection", so "Fun2" won't execute the AOP injection of "CustomerAttributeForClass".

**Comment by davidfowl** [comment]
This is being done over in new signalr (we're actually not starting with a pipeline at all).

**Comment by MaleDong** [comment]
@davidfowl ：Oh？Can you explain it in details?

**Comment by davidfowl** [comment]
New SignalR is over here https://github.com/aspnet/SignalR. There's no pipeline anymore. All we have right now (and it's still early) so far is https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR/HubLifetimeManager.cs. Any features we add on top will be scenario driven. Right now we're in the "make it work" and "understand what the boilerplate looks like before adding it to the framework" phase.
