### ISSUE TITLE
Fails fresh VS2015 build

### ISSUE THREAD

**Issue by ericis** [aspnet/SignalR-Server#104]
_Environment:_ Win 8.1, VS2015 RC Enterprise

__Steps to repro:__
  1. clone repo (git clone ...)
  2. open solution in VS
  3. Set sample as start-up project
  4. Build just sample project (right-click -> build)
  5. look at 17,742 errors (yikes)
  6. Close VS
  7. Re-open VS
  8. Clean sample project
  9. Build sample project
  10. Look at 20,003 errors LOL

**Comment by ericis** [comment]
I couldn't run `build.cmd` either until I manually copied `nuget.exe` into the `.nuget` folder relative to the solution (tried as admin first too and checked the `AppData\Local folder`).  Once `nuget.exe` was found, `build.cmd` ran fine and then I could build and run in VS2015.

The samples that are there are working great!

**Comment by muratg** [comment]
@ericis So is this good to close?

**Comment by ericis** [comment]
@muratg I'd still like to see a clean build work.  If someone can confirm "works on my machine" (after deleting any local copies/setup, inc. the local NuGet install in AppData), then maybe we can close?

**Comment by ericis** [comment]
I confirmed the fresh fail on my Win 8.1 system:
  1. Deleted `"%LocalAppData%\NuGet"`
  2. Opened VS2015 (only 1 instance)
  3. Cloned SignalR-Server Git using Team Explorer Git integration directly to new local folder
  4. Build (`Ctrl+F6`)
      _19,979 errors_ :boom: 
  5. Open command prompt to local repo copy
  6. Run `build.cmd` :boom: 

Fails with:

    E:\src\trash>build.cmd
    Downloading latest version of NuGet.exe...
    The system cannot find the path specified.
    Invoke-WebRequest : Could not find a part of the path 'C:\Users\Eric Swanson\AppData\Local\NuGet\NuGet.exe'.
    At line:1 char:43
    + $ProgressPreference = 'SilentlyContinue'; Invoke-WebRequest 'https://www.nuget.o ...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], DirectoryNotFoundException
        + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
    
    A subdirectory or file .nuget already exists.
    '.nuget\NuGet.exe' is not recognized as an internal or external command,
    operable program or batch file.
    '.nuget\NuGet.exe' is not recognized as an internal or external command,
    operable program or batch file.
    The system cannot find the path specified.
    The system cannot find the path specified.
    The system cannot find the path specified.
    The system cannot find the path specified.

**Comment by moozzyk** [comment]
Build should work now.
