### ISSUE TITLE
app.UseSignalR(); missing in VS 2015 RC

### ISSUE THREAD

**Issue by mrchief** [aspnet/SignalR-Server#105]
On a fresh new project, adding the latest package, this line fails to compile:

```csharp
app.UseSignalR();
```

Intellisense confirms there is no such method.

**Comment by davidfowl** [comment]
Did you add the right reference?

**Comment by mrchief** [comment]
Yeah, I verified with the sample too and they are same. But since I added thru Nuget, wouldn't that add the right ones?

**Comment by davidfowl** [comment]
Can you show me the reference

**Comment by mrchief** [comment]
Here's the project.json:

```json
{
    "webroot": "wwwroot",
    "userSecretsId": "aspnet5-WebApplication1-f1adc795-f7ec-4e78-8e31-4f94b6847920",
    "version": "1.0.0-*",

    "dependencies": {
        "EntityFramework.SqlServer": "7.0.0-beta4",
        "EntityFramework.Commands": "7.0.0-beta4",
        "Microsoft.AspNet.Mvc": "6.0.0-beta4",
        "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta4",
        "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta4",
        "Microsoft.AspNet.Authentication.Facebook": "1.0.0-beta4",
        "Microsoft.AspNet.Authentication.Google": "1.0.0-beta4",
        "Microsoft.AspNet.Authentication.MicrosoftAccount": "1.0.0-beta4",
        "Microsoft.AspNet.Authentication.Twitter": "1.0.0-beta4",
        "Microsoft.AspNet.Diagnostics": "1.0.0-beta4",
        "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta4",
        "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta4",
        "Microsoft.AspNet.Server.IIS": "1.0.0-beta4",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-beta4",
        "Microsoft.AspNet.StaticFiles": "1.0.0-beta4",
        "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta4",
        "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta4",
        "Microsoft.Framework.ConfigurationModel.UserSecrets": "1.0.0-beta4",
        "Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-beta4",
        "Microsoft.Framework.Logging": "1.0.0-beta4",
        "Microsoft.Framework.Logging.Console": "1.0.0-beta4",
        "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta4",
        "Microsoft.AspNet.SignalR.Server": "3.0.0-beta5"
    },

    "commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000",
        "gen": "Microsoft.Framework.CodeGeneration",
        "ef": "EntityFramework.Commands"
    },

    "frameworks": {
        "dnx451": { }
    },

    "exclude": [
        "wwwroot",
        "node_modules",
        "bower_components"
    ],
    "publishExclude": [
        "node_modules",
        "bower_components",
        "**.xproj",
        "**.user",
        "**.vspscc"
    ],
    "scripts": {
        "postrestore": [ "npm install", "bower install" ],
        "prepare": [ "gulp copy" ]
    }
}
```

I also see few of these errors (although first time build succeeded). I suspect something else is messed up (other than SignalR)...

> Severity	Code	Description	Project	File	Line
Error	CS0433	The type 'AuthenticationDescription' exists in both 'Microsoft.AspNet.Http.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Microsoft.AspNet.Http, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'	WebApplication1.DNX 4.5.1	c:\src\visual studio 2015\Projects\WebApplication1\src\WebApplication1\Models\ManageViewModels.cs	24

**Comment by mrchief** [comment]
While trying to find a solution for this, I went ahead and updated all packages to their latest. Somehow, that cleaned up things and now I can see `.UseSignalR()`. 

I still get weird errors like this

![image](https://cloud.githubusercontent.com/assets/781818/8634565/875bec7e-27cb-11e5-84a8-9a62ded42087.png)

which I think are because of the beta churn that these packages are going through. Still makes it a pain for us devs to sort through these but I'm hoping the final release will iron out these petty issues.
