### ISSUE TITLE
Entity Framework DbContext in SignalR hub has wrong scope

### ISSUE THREAD

**Issue by yongyi781** [aspnet/SignalR-Server#106]
When a DbContext is injected into a SignalR hub, the same DbContext is used over multiple instances of the hub. This is different from the behavior when a DbContext is injected into a controller, where a new one is created every time a new instance of a controller is created. This seems like a bug, I think.

**Comment by BrannonKing** [comment]
DbContext is not thread-safe. You need one for each thread. The hubs are transient, and I believe they are instantiated and executed on the thread pool. Each call will end up on a different thread. Either construct the DbContext for each call, or forward the calls to some kind of periodically-processing thread.

**Comment by yongyi781** [comment]
Actually it doesn't matter that it's a DbContext. This applies to all services that were added with .AddScoped<>().

**Comment by halter73** [comment]
WebSockets should probably have a scope created per invocation to match the semantics of the other transports.

**Comment by byatis** [comment]
Is there any news or beta build coming soon for this? This is a show-stopper for our net core project migration which is using EF and SignalR
