### ISSUE TITLE
camelCase Serializer

### ISSUE THREAD

**Issue by e-pankov-parc** [aspnet/SignalR-Server#107]
How can I change json by default serializer to camelCase in SignalR?

**Comment by radu-matei** [comment]
Is there any progress on this, I would also like to know how to use the camelCase contract resolver in SignalR 0.2.0-alpha1-22107.

Thanks!

**Comment by radu-matei** [comment]
I figured out how to use, you can find it in [this StackOverflow answer](http://stackoverflow.com/a/39410434/3084239).

Basically, the idea is from #115 and the execution of the contract resolver [from this old SignalR issue](https://github.com/SignalR/SignalR/issues/500#issuecomment-7453751).

Hope this helps!
