### ISSUE TITLE
Customized JsonSerializer breaks SignalR 

### ISSUE THREAD

**Issue by saikatguha** [aspnet/SignalR-Server#115]
### Problem
I need to use non-default ```JsonSerializerSettings``` since client code expects certain options (e.g., ```CamelCasePropertyNamesContractResolver``` and ```DefaultValueHandling.Ignore```). There does not appear to be an easy way to invoke client calls from the Hub with custom serializer settings.

If in ConfigureServices I add ```services.AddSingleton(s => JsonSerializer.Create(...customSettings...))``` then Hub connections from the client stop working completely.

Note: aspnet MVC allows setting custom formatters through ```options.OutputFormatters```. There does not appear to be any corresponding config option for SignalR.

### Steps to reproduce
1. Create ViewModel: ```class A { string B; string C; }```
2. Call ```DemoHub.Clients.Caller.invoke(new A { B = "b"})```
3. Call ```console.log``` on client

### Actual Results
```{B: "b", C: null}```

### Desired Results
```{b:"b"}```

**Comment by larrifax** [comment]
The problem is that the SignalR client is expecting PascalCased data from the SignalR server, and thus crashes when it gets CamelCased data.

I managed to get it working using the `SignalRContractResolver` from [here](https://github.com/SignalR/SignalR/issues/500#issuecomment-7453751).

**Comment by saikatguha** [comment]
Thanks, I'll give it a try. 

Non-isolation of Json serialization settings between framework data and user data should be considered a bug though.

**Comment by muratg** [comment]
Investigate

**Comment by stajs** [comment]
I'm not sure about the handling of the null properties, but as far as camel casing goes and being serialization agnostic, @davidfowl [said](https://github.com/aspnet/SignalR-Server/issues/196#issuecomment-246089801):

> Don't worry, we're going to be working on that as part of this release.

In the meantime, @radu-matei [stackoverflowed](http://stackoverflow.com/a/39410434/2685650)/[blogged](https://radu-matei.github.io/blog/aspnet-core-mvc-signalr/) a workaround.

**Comment by muratg** [comment]
In SignalR Core, this won't be relevant any more per the new design.  You will be able to specify different formatters -- for an example, see https://github.com/davidfowl/Sockets/blob/master/samples/SocketsSample/Startup.cs#L49-L51
