### ISSUE TITLE
Custom serializer

### ISSUE THREAD

**Issue by buybackoff** [aspnet/SignalR-Server#118]
Currently, JsonSerializer is used to serialize an object to a `BinaryMemoryPoolTextWriter`, and then its Buffer property is used to send bytes, e.g. `context.Transport.Context.Response.Write(writer.Buffer);` or `socket.Send(writer.Buffer).PreserveCulture();`. As far as I understand from code, it is quite easy to abstract JsonSerializer to an interface like this:

```
public interface ISerializer {
        byte[] Serialize<T>(T value);
        T Deserialize<T>(byte[] bytes);
    }
```
For many cases, the overhead of SignalR is more than OK compared to usability and API. But in other, Json serialization is not needed and just wrong for a task, e.g. if I send many small structs, I could marshal then directly from byte buffers.

Is there any hope to see the serializer abstraction? Would you accept such a pull request?

Another option is to check if `T` is `byte[]` and avoid Json completely in this case. That is much simpler to implement.

**Comment by davidfowl** [comment]
Nope there's just so much downstream impact of abstracting the serialization. It's not as simple as declaring an interface. Clients also new to change, the framing needs to change. It requires more careful thought and it's not something we'd take as a PR

**Comment by BrannonKing** [comment]
@buybackoff, are you using a C# client or a JavaScript client? The use of JToken in the message class for partial deserialization is the issue.
.

**Comment by buybackoff** [comment]
I am using C#.
