### ISSUE TITLE
Not registering in ServiceCollection [Bug]

### ISSUE THREAD

**Issue by gvx111** [aspnet/SignalR-Server#119]
I'm using SDK: "version": "1.0.0-beta8-15120", and signalr version is 3.0.0-beta5
<pre>MissingMethodException: Method not found: 'Boolean Microsoft.Framework.DependencyInjection.ServiceCollectionExtensions.TryAdd(Microsoft.Framework.DependencyInjection.IServiceCollection, Microsoft.Framework.DependencyInjection.ServiceDescriptor)'.
</pre>

**Comment by BrennanConroy** [comment]
Do not mix beta versions. If you use beta 8 dnx then use beta 8 packages. Secondly SignalR 3 is on hiatus (on hold) so its probably not a good idea to try to use it in vNext right now. We stopped shipping the package on NuGet so you can't use it with newer versions of dnx as you found out.
