### ISSUE TITLE
Internal server error when using with ASP.NET vNext beta7

### ISSUE THREAD

**Issue by BalassaMarton** [aspnet/SignalR-Server#121]
Steps to reproduce:
1. Create new ASP.NET 5 web application
2. Ensure that all ASP.NET packages are beta7
3. Install SignalR.Server 3.0.0-beta5 (latest as of today)
4. Append the following to `Startup.ConfigureServices`
```cs
services.AddSignalR();
```
5. Insert the following line in `Startup.Configure` before the call to `app.UseMvc`
```cs
app.UseSignalR();
```
6. Run the application. You will get an internal server error (System.MissingMethodException)

**Comment by BrennanConroy** [comment]
SignalR 3 is on hold, so you will find it next to impossible to use in its current state. See https://github.com/aspnet/Home/wiki/Roadmap#future-work

**Comment by BalassaMarton** [comment]
It worked fine up until beta 5 :( Can I at least use SignalR 2.2.0 with ASP.NET 5?

**Comment by Eilon** [comment]
@BalassaMarton you can try it out - it might theoretically work as long as you don't use Web Sockets.

**Comment by BalassaMarton** [comment]
It seems to work, and you're right, it's not using web sockets (although I don't see why)

**Comment by MaxxDelusional** [comment]
@BalassaMarton How did you get 2.2.0 to work? Can you have multiple startup classes? Where did you call app.MapSignalR()?

**Comment by BalassaMarton** [comment]
@MaxxDelusional
(1) Add SignalR to the request pipeline using the technique described here:
http://stackoverflow.com/questions/32890084/using-signalr-2-in-asp-net-5-application

(2) To leverage the new DI framework in your hubs, you need a dependency resolver. My version looks like this:
```cs
    public class DependencyResolverAdapter : DefaultDependencyResolver
    {
        private readonly IServiceProvider _serviceProvider;

        public DependencyResolverAdapter(IServiceProvider serviceProvider)
        {
            _serviceProvider = serviceProvider;
        }

        public override object GetService(Type serviceType)
        {
            return _serviceProvider.GetService(serviceType) ?? base.GetService(serviceType);
        }

        public override IEnumerable<object> GetServices(Type serviceType)
        {
            return _serviceProvider.GetServices(serviceType).Concat(base.GetServices(serviceType));
        }
    }
```
Insert this into `Startup.Configure` (probably after the `UseOwin` call):
```cs
GlobalHost.DependencyResolver = new DependencyResolverAdapter(app.ApplicationServices);
```
