### ISSUE TITLE
How Register HubRoute

### ISSUE THREAD

**Issue by GVX111** [aspnet/SignalR-Server#122]
I have two project. First project is Startup and second is Signar Project.
From second project i'm using serviceCollection.BuildServiceProvider().GetService<IApplicationBuilder>().UseSignalR();
Also i have [HubName("Auction")]
    public class AuctionHub : Microsoft.AspNet.SignalR.Hub 
And application can't generate hub for Auction.
If i add UserSignalR It working correctly. 
I think its problem of Routes.

**Comment by muratg** [comment]
SignalR 2.*?

**Comment by gvx111** [comment]
Signalr 3
