### ISSUE TITLE
Does the signalr v3 can run with kestrel?

### ISSUE THREAD

**Issue by Kagamine** [aspnet/SignalR-Server#126]
Does the signalr v3 can run with kestrel?

**Comment by MJomaa** [comment]
@Kagamine yes. You can use for example the 2.2 js client and the v3 signalr backend. AFAIK it won't be actively developed until RTM ships since other parts of the asp.net 5 stack are more important for now. There are some issues on *nix, however long polling works.

**Comment by Kagamine** [comment]
Can I mix v2 and v3 in a same project?

**Comment by MJomaa** [comment]
For the server: Not sure, never tried. Why would one mix v3 and v2 for the server side anyway?
For the client: There is afaik only v2 client available.

For both: v2 client and v3 server should work (for now).

**Comment by Kagamine** [comment]
@MJomaa How to call a hub in a Controller? (SignalR v3)

**Comment by MJomaa** [comment]
(sry I'm on mobile)

Inject this into your controller:

```IConnectionManager connectionManager```


Get the Hub context:

```_myHub = connectionManager.GetHubContext<MyHub>();```

**Comment by Kagamine** [comment]
@MJomaa Thank you very much!!!!

**Comment by Kagamine** [comment]
![image](https://cloud.githubusercontent.com/assets/2216750/11025870/499d28b0-86dc-11e5-81b4-2d3afec922b6.png)

@MJomaa  There was no interface named `IConnectionManager`

**Comment by davidfowl** [comment]
IHubContext<THub>

**Comment by Kagamine** [comment]
@davidfowl thx

**Comment by MJomaa** [comment]
@Kagamine Na not as a service. You actually added SignalR to the DI-Container already. You can Inject IConnectionManager directly into your constructor. However inject what David says :+1: 

@davidfowl Oh, good to know!
