### ISSUE TITLE
hub [signalr/hubs]

### ISSUE THREAD

**Issue by GVX111** [aspnet/SignalR-Server#131]
FileNotFoundException: Could not load file or assembly 'Microsoft.Dnx.Runtime.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)

**Comment by moozzyk** [comment]
I believe this is fixed now.
