### ISSUE TITLE
Someone update services.

### ISSUE THREAD

**Issue by GVX111** [aspnet/SignalR-Server#132]
InvalidOperationException: Unable to resolve service for type 'Microsoft.Dnx.Runtime.ILibraryManager' while attempting to activate 'Microsoft.AspNet.SignalR.Hubs.DefaultAssemblyLocator'

**Comment by GVX111** [comment]
changes 
<pre>using Microsoft.Dnx.Runtime; to using Microsoft.Extensions.PlatformAbstractions;</pre>
https://github.com/aspnet/SignalR-Server/blob/b5985baa5da72ae5d2bec7c54a841c6e9c1c8e72/src/Microsoft.AspNet.SignalR.Server/Hubs/DefaultAssemblyLocator.cs

**Comment by HenryGarle** [comment]
Sadly SignalR has been pushed out of RC into ... Q3 next year. I would not hold your breath.

**Comment by davidfowl** [comment]
Send a pull request.

**Comment by moozzyk** [comment]
This has been done.
