### ISSUE TITLE
OnReconnected is not awaited

### ISSUE THREAD

**Issue by rmja** [aspnet/SignalR-Server#137]
Nothing waits for OnReconnected to finish async operation before any other hub function is invoked.

```
public override async Task OnReconnected()
{
    await somethingAsync();
}

public async Task SomeAsyncHubFunction()
{
    // Expect this function to be run efter somethingAsync completes. This expectation does not hold.
}
```

Putting async code in OnConnected() in a hub works as expected. That is, SomeAsyncHubFunction is always called after the OnConnected call completes. This is ensured by the `await` in https://github.com/aspnet/SignalR-Server/blob/dev/src/Microsoft.AspNet.SignalR.Server/PersistentConnection.cs#L506.

```
public override async Task OnConnected()
{
    await somethingAsync();
}

public async Task SomeAsyncHubFunction()
{
    // Expect this function to be run efter somethingAsync completes. This expectation holds.
}
```

**Comment by rmja** [comment]
The transport is long polling

**Comment by muratg** [comment]
https://github.com/aspnet/SignalR-Server/issues/212
