### ISSUE TITLE
Error Handler

### ISSUE THREAD

**Issue by staff0rd** [aspnet/SignalR-Server#141]
In the previous version it was possible to handle errors as follows.  Is similar functionality currently available in v3?  I note that `HubPipelineModule` does not have `OnIncomingError`...

~~~
public class SignalrErrorHandler : HubPipelineModule
{
    protected override void OnIncomingError(ExceptionContext exceptionContext, IHubIncomingInvokerContext invokerContext)
    {
        Trace.WriteLine(exceptionContext.Error.Message);
        base.OnIncomingError(exceptionContext, invokerContext);
    }
}
~~~

**Comment by davidfowl** [comment]
Of course it does https://github.com/aspnet/SignalR-Server/blob/dev/src/Microsoft.AspNet.SignalR.Server/Hubs/Pipeline/HubPipelineModule.cs#L347

**Comment by staff0rd** [comment]
Shame on me, I typed `public override`...
