### ISSUE TITLE
A way to get SignalR endpoints list

### ISSUE THREAD

**Issue by DovydasNavickas** [aspnet/SignalR-Server#143]
**Context**

I am working with AspNet 5 SignalR server with JwtBearerAuthentication (Microsoft.AspNet.Authentication.JwtBearer), https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Samples/issues/2.

In order to authenticate SignalR connection with token reliably on all platforms, I have to use query string to pass it, because WebSockets specification does not require Headers for socket requests (even though .NET client implements that)

**Problem**

I need to determine if current request is being served by SignalR.

**Question**

How can I get a list of SignalR endpoints to check if the endpoint is there

OR

A way to check if the connection is being served by SignalR middleware

**Use case**

The actual code where I need this can be found [here](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Samples/blob/master/samples/SignalR/HelloSignalR/Startup.cs#L50-L57):

``` csharp
app.UseJwtBearerAuthentication(options => {
    options.Events = new JwtBearerEvents {
        // Note: for SignalR connections, the default Authorization header does not work,
        // because the WebSockets JS API doesn't allow setting custom parameters.
        // To work around this limitation, the access token is retrieved from the query string.
        OnReceivingToken = context => {
            // Note: when the token is missing from the query string,
            // context.Token is null and the JWT bearer middleware will
            // automatically try to retrieve it from the Authorization header.

            // >>> Here i need to check if the connection is served by signalr
            // >>> And if not, simply not take token from query string
            context.Token = context.Request.Query["access_token"];

            return Task.FromResult(0);
        }
    };
});
```

As I have posted an SO question [here](http://stackoverflow.com/questions/33948970/how-to-get-signalr-endpoints-list-in-vnext) and got no proper answer, I guess it might not be possible in SignalR today, but maybe that could be a feature worth thinking of for SignalR 3 then?

**Comment by davidfowl** [comment]
There's no way to get end points from inside the application. Not really a SignalR question but more of an ASP.NET question.
