### ISSUE TITLE
Group broadcast message not working

### ISSUE THREAD

**Issue by NicolasLaw** [aspnet/SignalR-Server#152]
**Context**

I'm new on SignalR and I am working with AspNet 5. I'm having trouble sending message to clients inside a specific group. 

**Code**
```
public async Task Juin(string userId)
        {
            if (!string.IsNullOrEmpty(userId))
            {
                await Groups.Add(Context.ConnectionId, userId);
                Clients.Group(userId).newMessage( "hello world.");
            }
        }
```

But sending message to "All" Clients works.

`Clients.All.newMessage( "hello world.");`

Am i missing something or is there a specific configuration ?

Thank you for your help.

**Comment by ChiefWiggum** [comment]
I'm having issues with the groups as well. My clients sign up at the hub with a method called SubscribeForUpdates where they get added to a language specific group. I can see that the method gets called when debugging it. I then try to send language specific updates to all supported language groups and this code gets called as well, but the clients never receive an update from the hub when I send it to their group, only to all clients.
**Adding clients to a language group**
   ```
 [HubName("notification")]
 public class NotifyHub : Hub
{
    public void SubscribeForUpdates()
    {
        var groupName = $"{CultureInfo.CurrentCulture.TwoLetterISOLanguageName}";
        Groups.Add(Context.ConnectionId, groupName);
    }
}
```
**Sending an update**
This does not work:
`_hubContext.Clients.Group(groupName).MyAwesomeUpdate(new JsonResult(myData));`

But this does:
`_hubContext.Clients.All.MyAwesomeUpdate(new JsonResult(myData));`

**Comment by NicolasLaw** [comment]
I spent two day on this problem, i finally rollback to signalR 2.2. Without modifying my code, everything works now.

**Comment by junaiddotnet** [comment]
If. Caller not getting call , do other way around by calling callers . Like client.caller

**Comment by ChiefWiggum** [comment]
@NicolasLaw So you are using AspNet Core RC1 with SignalR 2.2 as described here?
http://stackoverflow.com/a/32921505/2360972
Or are you doing something else?

@junaiddotnet 
Sorry I don't understand what you mean

**Comment by NicolasLaw** [comment]
@ChiefWiggum Yes. Here is my post. You can find solution I used : 
http://stackoverflow.com/a/35198916/3220048

**Comment by SuperTroye** [comment]
I'm having the same problem too. Spent two days on this. I am using Microsoft.AspNet.SignalR.Server: 3.0.0-rc1-final with aspnet5

Will revert back to 2.2.0 and see if it fixes the problem

**Comment by bbjoern** [comment]
Having the same problem ! Microsoft.AspNet.SignalR.Server: 3.0.0-rc1-final with aspnet5. Can someone please comment if and when the problem will be fixed ?

**Comment by moozzyk** [comment]
I fixed an issue where groups did not work when using js client and longPolling. In the process I tried both js and C# client and longPolling, webSockets and serverSentEvent transports and groups worked. If it still does not work for you please create a new issue and provide a repro.
