### ISSUE TITLE
DI issue on .NET CLI

### ISSUE THREAD

**Issue by AndreiGorlov** [aspnet/SignalR-Server#154]
Trying to migrate my project on dotnet cli.
Got exception when accessing api controller that injects IHubContext:
```
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.PlatformAbstractions.ILibraryManager' while attempting to activate 'Microsoft.AspNetCore.SignalR.Hubs.DefaultAssemblyLocator'.
```
Pretty sure its related to https://github.com/aspnet/Announcements/issues/149

**Comment by moozzyk** [comment]
What is your runtime version and what version of package you are using?

**Comment by andreigorlov** [comment]
"sdk": {
    "version": "1.0.0-rc2-16541"
  }

"Microsoft.AspNetCore.SignalR.Server/0.1.0-rc2-16240"

**Comment by moozzyk** [comment]
Thanks for the repro - I was able to duplicate the issue

**Comment by AndreiGorlov** [comment]
Seems fixed in https://github.com/aspnet/SignalR-Server/commit/f2c308caeb60599c5c9994c94a3d754c599c547d
Thanks @pranavkm
