### ISSUE TITLE
SignalR Server custom authorization

### ISSUE THREAD

**Issue by SimoVasilev** [aspnet/SignalR-Server#158]
I have to make custom authorization. For the version 2.2.0 i found example (http://www.asp.net/signalr/overview/security/persistent-connection-authorization):
```
public class AuthenticatedConnection : PersistentConnection 
{ 
    protected override bool AuthorizeRequest(IRequest request) 
    { 
        return request.User.Identity.IsAuthenticated; 
    } 
} 
```

But in the version 3.0 the example doesn't work. How can I enforce authorization of requests and make some custom logic?

**Comment by moozzyk** [comment]
I tried and the AuthorizeRequest method on the derived class was called. Make sure you register your connection with `app.UseSignalR<AuthenticatedConnection>(url);` otherwise the server will not be aware of the derived class.
