### ISSUE TITLE
Authorize attribute on methods

### ISSUE THREAD

**Issue by Stalso** [aspnet/SignalR-Server#160]
Hello. When I mark my hub with Authorize attribute ( I am using jwt token middleware for authorization), everything is OK. Server responds with 401 code, if user is unathorized and is not connected. But if I mark only one method of my hub with this attribute, method is not called (it is correct) , but server responds with 200 code (with Execption data) . How can I retrun 401 code from server, when protected method of hub was called?

**Comment by muratg** [comment]
Current POR: we'll have something like "SignalRAuthorize" for duplex, and we'll use the common one (#67) for incoming.

**Comment by muratg** [comment]
Also see #67
