### ISSUE TITLE
Wrong DI scope in SignalR

### ISSUE THREAD

**Issue by maximtarasov** [aspnet/SignalR-Server#161]
Hello.

I have application which uses ASP.NET MVC vNext (RC1) + EntityFramework 7 (RC1) + SignalR.
**I found, that services registered via AddScoped - injected as singletons.**

The most problem caused by this - with EntityFramework. When you are using AddDbContext<> - DbContext registers as scoped by default, and there is no options to register context as transient. And to use DbContext in SignalR app - the only way to make workaround for AddDbContext<>.

Here is an issue where this practice was described: aspnet/EntityFramework#1112

**Comment by rmja** [comment]
I just found out that I am having the same issue. I was looking for a quick fix, and came up with the following:
In https://github.com/aspnet/SignalR-Server/blob/dev/src/Microsoft.AspNetCore.SignalR.Server/Hubs/DefaultHubActivator.cs#L31 I have replaced:
```
return ActivatorUtilities.CreateInstance(_serviceProvider, descriptor.HubType) as IHub;
```
with:
```
return ActivatorUtilities.CreateInstance(_contextAccessor.HttpContext.RequestServices, descriptor.HubType) as IHub ?? ActivatorUtilities.CreateInstance(_serviceProvider, descriptor.HubType) as IHub;
```

where `_contextAccessor` is an `IHttpContextAccessor` injected in the constructor.

**Comment by yongyi781** [comment]
Ok, so I found out that this is because it's using the scope of the SignalR request, which is by nature long-running (since this is how SignalR works). That seems like a bad choice of scope for a DbContext, though.

**Comment by muratg** [comment]
Dup: #106
