### ISSUE TITLE
Kill connection from server

### ISSUE THREAD

**Issue by Bortxx** [aspnet/SignalR-Server#162]
There seems to be no way to kill client connections from the server. Moving to SignalR from WCF which has this feature. Imagine an unwanted client that you want to ban at least temporarily based on IP. How would this be done in SignalR?

**Comment by BrannonKing** [comment]
You could do this easily farther up the Owin chain. Something like this:

```csharp
app.Use((context, taskFactory) =>
{
  if (context.Request.Host != bad) return taskFactory.Invoke();
  return null; 
}
```

**Comment by Bortxx** [comment]
That was just an example. In real life I just want to kill one SignalR connection by ConnectionID not by IP?

**Comment by davidfowl** [comment]
There's no API for this currently. You can send a message to the client and call stop on the client side in response. We'll look at a first class API in the next major version.

**Comment by uclaitsscott** [comment]
How do we go about stopping a malicious connection?

**Comment by davidfowl** [comment]
Any API at the SignalR layer is going to do that anyways. The only difference would be that user code on the client wouldn't see the message.

You can abort the connection (using the HttpContext) but a SignalR client will just reconnect...

**Comment by uclaitsscott** [comment]
Well I'm thinking if you are able to abort the connection and have a sufficient middleware like various OWIN ip address banning implementations I've seen, it could be a feasible solution.

**Comment by davidfowl** [comment]
Not sure what you mean.

**Comment by uclaitsscott** [comment]
Consider a chat room with signalr. You get a malicious user you want to boot. If you rely on telling their client to disconnect, they could very easily ignore that disconnect request. If you roll some OWIN based middleware that is checking each request, you could in theory reject any request from them.

**Comment by davidfowl** [comment]
Sure, but that's not SignalR, that's middleware. It's like trying to reject a malicious user at any point in the stack. A SignalR API needs to look at the fact that there might be a SignalR client connected and that it will reconnect if you just abort the connection.

If you're talking about somebody sending arbitrary http requests to the SignalR end point that "look like" a signalr client then you basically need to re-implement all of the knowledge signalr has about the protocol and then abort the http request.

**Comment by JanEggers** [comment]
from my point of view this discussion is about auth.

you need to secure your hub using auth and then ban / disable the user/group/whatever you want gone.

as @davidfowl pointed out anything reliing on connectionid will just make the client reconnect

**Comment by moozzyk** [comment]
I guess you could reject disconnected client by overwriting the `AuthorizeRequest` method and returning false if you don't want the client to reconnect/start a new connection.
