### ISSUE TITLE
hub registration

### ISSUE THREAD

**Issue by Bortxx** [aspnet/SignalR-Server#167]
I wish there was a way to explicitly register the hub endpoints like it is possible with the 
"persistent connection" model. Right now hubs are registered through reflection and all classes inheriting from the Hub class are registered as endpoints. So you can't pick and choose which hubs will be active at run-time.

So there is no way for example to enable/disable a hub at run-time or initialize or release resources as a hub in my hub pool may no longer be needed. I have shared expensive objects in some of the hubs that I wish I could dispose of when some logic determines that a particular hub can be disabled.

**Comment by muratg** [comment]
This needs design. @anurse Could you follow-up?

**Comment by davidfowl** [comment]
We're looking at this with the new model

**Comment by Bortxx** [comment]
So in what version might I expect to see the new model? And what will the new model be?

**Comment by davidfowl** [comment]
You can see the current sample here https://github.com/aspnet/SignalR
