### ISSUE TITLE
How do you obtain a SignalR context from outside of Hubs?

### ISSUE THREAD

**Issue by stajs** [aspnet/SignalR-Server#171]
[Previously, the recommended method was to use the `GlobalHost`](http://www.asp.net/signalr/overview/guide-to-the-api/hubs-api-guide-server#callfromoutsidehub). This no longer seems to be available, so is there a new way to do this?

**Comment by stajs** [comment]
I asked too soon. Some further poking around the source code, revealed that there is still a `ConnectionManager`, so wiring up the DI:

```
services.AddSingleton<ConnectionManager>();
```

... allowed it to be injected and used:

```
public class JimboHandler : INotificationHandler<Jimbo>
{
	private readonly IHubContext _context;

	public JimboHandler(IConnectionManager connectionManager)
	{
		_context = connectionManager.GetHubContext<DraftHub>();
	}

	public void Handle(Jimbo notification)
	{
		_context.Clients.All.jimbo();
	}
}
```

**Comment by davidfowl** [comment]
You can inject `IHubContext<DraftHub>` directly

**Comment by stajs** [comment]
Amazeballs. Thanks for the tip!
