### ISSUE TITLE
Package can't be resolved with RC2

### ISSUE THREAD

**Issue by AloeDream** [aspnet/SignalR-Server#175]
it relies on Microsoft.AspNet.* packages, but now they are Microsoft.AspNetCore.*, so..

**Comment by BrennanConroy** [comment]
What? This project is referencing Microsoft.AspNetCore.*

**Comment by AloeDream** [comment]
@BrennanConroy, maybe I did something wrong, but it showed error and named about 4 Microsoft.AspNet.* dependencies can't be resolved.
Have you already tried to add this package in RC2 web project?

**Comment by BrennanConroy** [comment]
Thats probably because you're grabbing the beta5 version on NuGet. This project is on hiatus so we aren't releasing it. If you really want to use it then you can reference one of our myget feeds or reference it from source.

**Comment by AloeDream** [comment]
@BrennanConroy no, it's `3.0.0-rc1-final` from myget feed.
I wasn't able to build sources as it probably requires some build tools. I'm not a contributor, just a developer, who uses this lib.

**Comment by BrennanConroy** [comment]
RC1 is the previous release, so you would need RC2 if you're doing RC2 development

**Comment by AloeDream** [comment]
@BrennanConroy you're right! Thanks!

**Comment by AloeDream** [comment]
So it's gonna be `"Microsoft.AspNetCore.SignalR.Server": "0.1.0-rc3-20925"` from `https://www.myget.org/F/aspnetcidev/api/v3/index.json`?
I was using `https://www.myget.org/F/aspnetmaster/api/v3/index.json` repository.

**Comment by AloeDream** [comment]
@BrennanConroy or I should use `https://www.myget.org/gallery/aspnetwebstacknightly` repository?

**Comment by BrennanConroy** [comment]
https://www.myget.org/F/aspnetvnext/api/v3/index.json, but that is RC3. Just making sure you know, this project isn't supported yet so any issues you hit will not be fixed by us until we start working on this project.

**Comment by AloeDream** [comment]
@BrennanConroy are you sure? I see only 2 packages in this repository:
`https://www.myget.org/gallery/aspnetvnext`

![default](https://cloud.githubusercontent.com/assets/13584857/15331818/214d83ea-1c74-11e6-90b1-973aad8f2b98.png)

**Comment by AloeDream** [comment]
@BrennanConroy so where do I get RC2 version? And is there already JS lib and ts definitions available for v3?

**Comment by moozzyk** [comment]
I think the best bet is not using aspnetvnext feed (which already has rc3 packages) but https://myget.org/gallery/aspnetrelease feed. It has the latest SignalR rc2 package.

**Comment by AloeDream** [comment]
@moozzyk thanks! There just so many various different versions of asp repository, that it's really confusing. It would be very helpful to have this info in `README.MD`
