### ISSUE TITLE
Move WebSocket transport implementation in a different assembly

### ISSUE THREAD

**Issue by Yves57** [aspnet/SignalR-Server#188]
I know that SignalR will be entirely refactored after ASP.NET Core 1.0, and so I suggest to move the WebSocket transport implementation in a different assembly.
If I don't want to use it (some routers and anti-virus don't like it), it is not necessary to have dependencies on WebSocket assemblies.

**Comment by davidfowl** [comment]
We're not going to split out websockets into another assembly. In fact, websockets is built into ASP.NET Core's HttpContext so I'm not sure what you mean.

**Comment by Yves57** [comment]
Sorry I made a mistake. I was thinking that is had dependency on "Microsoft.AspNetCore.WebSockets.Server".
