### ISSUE TITLE
Be able to send binary data to clients

### ISSUE THREAD

**Issue by Yves57** [aspnet/SignalR-Server#189]
I need to send a large Javascript `ArrayBuffer` to a Web Page.
I can convert my data to a Base64 string, and restore the `ArrayBuffer` on the client side, but the performances are very poor.
My current workaround is to use a MVC Controller for the binary data, but it would be nice to be able to that directly in the Hub class.

**Comment by lextm** [comment]
Related to #196

**Comment by muratg** [comment]
We'll discuss this in the new protocol.
