### ISSUE TITLE
Not working on internal server Azure

### ISSUE THREAD

**Issue by Alados** [aspnet/SignalR-Server#192]
I used
"Microsoft.AspNetCore.SignalR.Server": "0.1.0-rtm-21431",
"Microsoft.AspNetCore.WebSockets.Server": "0.1.0",
All working on localhost, but when was publish on internal server not.

**Comment by BrennanConroy** [comment]
The actual error here would be helpful.

But I'm guessing it fails because the SignalR package isn't on NuGet so when the deployment script runs in Azure it only looks for packages in its cache and NuGet so it wont find the SignalR package.

**Comment by moozzyk** [comment]
@BrennanConroy I assume you are talking about NuGet deployment. But if you published from VS using WebDeploy it would copy all the binaries you need no?

**Comment by BrennanConroy** [comment]
Well if it does that then we need the actual error even more.

**Comment by Alados** [comment]
Yes, I used webdeploy for publishing on Azure. May be error in Entity Framework 7.
On localhost all is ok, but on remote server not working.

**Comment by Alados** [comment]
My Hub
```
public async Task NewConnection(string userName)
        {
            await Groups.Add(Context.ConnectionId, Context.User.Identity.Name);

            //Находим участников чата и проверяем существуют ли они
            var recipient = await _userManager.FindByNameAsync(userName);
            var sender = await _userManager.FindByNameAsync(a/*Context.User.Identity.Name*/);
            if (sender == null || recipient == null)
            {
                return;
            }

            //Получаем чат, если он есть отправляем его id на клиент, если нет, то создаём новый
            var chat = _chat.GetChatByTwoUserId(sender.Id, recipient.Id);
            if (chat != null)
            {
                //Отправляем историю сообщений
                Clients.Caller.ViewMessageHistory(
                    new ChatHistoryModel(
                        chat.Id,
                        chat.Messages.Select(
                            message =>
                                new MessageModel(message.Text, message.UserNameOfSender, message.UserNameOfRecipient,
                                    chat.Id, message.SendTime))
                            .ToList()
                        ));
                return;
            }

            //Добавляем новый чат
            chat = _chat.AddNewChat(new ChatModel(DateTime.UtcNow, new List<ApplicationUser>
            {
                recipient,
                sender
            }, new List<MessageModel>()).ToChatDto());

            //Отправляем id нового чата
            Clients.Caller.ViewMessageHistory(new ChatHistoryModel(chat.Id, null));
        }


        /// <summary>
        /// Отправляем сообщение
        /// </summary>
        /// <param name="message">Сообщение</param>
        /// <param name="userName">Получатель</param>
        /// <param name="chatId">Id чата</param>
        public async Task SendNewMessage(string message, string userName, int chatId)
        {
            //Находим пользователей в базе и проверяем, есть ли они.
            var recipient = await _userManager.FindByNameAsync(userName);
            var sender = await _userManager.FindByNameAsync(Context.User.Identity.Name);
            if (sender == null || recipient == null)
            {
                return;
            }

            //Отправляем сообщение и записываем его в базу
            var messageModel = new MessageModel(message, recipient.Login, sender.Login, chatId, DateTime.UtcNow);
            _chat.AddNewMessage(messageModel.ToChatMessageDto());
            Clients.Group(userName).GetNewMessage(messageModel);
        }

        /// <summary>
        /// Отключаем пользователя
        /// </summary>
        /// <param name="stopCalled"></param>
        /// <returns></returns>
        public override Task OnDisconnected(bool stopCalled)
        {
            Groups.Remove(Context.ConnectionId, Context.User.Identity.Name);
            return base.OnDisconnected(stopCalled);
        }
```

**Comment by kamranayub** [comment]
It's working for me in Azure, I just created a demo game for a talk I'm doing and was playing with friends. I did have to remember to enable Web Sockets in my web app but other than that, publishing it worked. Packages I'm using are:

```
"Microsoft.AspNetCore.SignalR.Server": "0.2.0-*",
 "Microsoft.AspNetCore.WebSockets.Server": "0.2.0-*"
```

**Comment by Alados** [comment]
I can't plug 
"Microsoft.AspNetCore.SignalR.Server": "0.2.0-*",
"Microsoft.AspNetCore.WebSockets.Server": "0.2.0-*"
and use version 0.1.0

**Comment by easysoft2k15** [comment]
I guess that in order to be able to use:
"Microsoft.AspNetCore.SignalR.Server": "0.2.0-*",
"Microsoft.AspNetCore.WebSockets.Server": "0.2.0-*"
I need to create the nuget package myself and tell to Visual Studio to consume it from the local disk.
Is this correct?
If so is it enough to point nuget tool to the \netstardart1.6\Microsoft.AspNetCore.SignalR.Server.dll in order to create the project?
Thank You

**Comment by kamranayub** [comment]
I am pointing to the aspnet vnext nuget feed. The sample app is now live on
GH if you need to reference: eonarheim/aspnet-demo-game

**Comment by kamranayub** [comment]
Sorry, aspnet-core-demogame actually, mistyped it.

**Comment by easysoft2k15** [comment]
It work! Thank You.
Just out of curiosity do You know why if I use the key
`<add key="AspNetVNext" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />`
in the nuget.config it find the package while if i put the same path in "Nuget Package Manager" => "Package Sources" in Visual Studio it does not find the package?

**Comment by easysoft2k15** [comment]
Never mind: I just misspelled the right address....
It works both way.

**Comment by easysoft2k15** [comment]
@kamranayub on Your project for some reasons I'm getting the error:
> Unable to resolve 'Microsoft.AspNetCore.WebSockets.Server (>= 0.2.0)' for '.NETCoreApp,Version=v1.0'
SignalR is working but I suspect is not using WebSocket.
Any idea why?

**Comment by kamranayub** [comment]
They were migrating packages to a new feed endpoint I think, perhaps that
impacted it? Not sure...

**Comment by easysoft2k15** [comment]
I change the nuget source key to:

>  <add key="AspNetCore" value="https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json" />

but this did not help.
More over the SignalR package is restore with no problem. Very strange...

**Comment by easysoft2k15** [comment]
@kamranayub At the end I was able to fix it. I made a pull request with the changes on Your repository.

**Comment by moozzyk** [comment]
Seems to be resolved. If this is not the case open a new issue.
