### ISSUE TITLE
SignalR 0.2.0-alpha1-21591 does not call OnConnected or OnReconnected functions in hub

### ISSUE THREAD

**Issue by bittrex-bill** [aspnet/SignalR-Server#195]
When I sync "Microsoft.AspNetCore.SignalR.Server": "0.2.0-*" from https://www.myget.org/F/aspnetvnext/api/v3/index.json I receive version 0.2.0-alpha1-21591.

The hubs connect and I'm able to call functions in my hub from my javascript.  However breakpoints in OnConnected and OnReconnected are never hit.  I cannot repro this from the latest source of SignalR-Server SignalRSample.Web.

**Comment by muratg** [comment]
Investigate.

**Comment by moozzyk** [comment]
I don't see this happen. If you still see this with latest bits please open a new issue and provide a repro.

**Comment by muratg** [comment]
@moozzyk Good to close?
