### ISSUE TITLE
AddSignalR options customization via IHostingEnvironment

### ISSUE THREAD

**Issue by kamranayub** [aspnet/SignalR-Server#197]
This seems like something people will run into as I did.

`ConfigureServices` does not accept an `IHostingEnvironment` so if I need to customize `SignalROptions` like this:

```
services.AddSignalR(options =>
{
  options.Hubs.EnableDetailedErrors = // only in development
});
```

I can seem to workaround this by doing:

```
var env = services.First(sd => sd.ServiceType == 
  typeof(IHostingEnvironment)).ImplementationInstance as IHostingEnvironment;

services.AddSignalR(options =>
{
  options.Hubs.EnableDetailedErrors = env.IsDevelopment();
});
```

Is this an intended side effect of having options in `ConfigureServices` vs. `Configure`? Or just a pre-RTM issue that'll be fixed?

**Comment by davidfowl** [comment]
You can get at the `IHostingEnvironment` via the Startup ctor. I'd suggest doing that instead of looking at the service collection

**Comment by kamranayub** [comment]
Ah OK and just reference a private field for it?

**Comment by davidfowl** [comment]
Yep
