### ISSUE TITLE
IhubContext not properly working outside of hub class

### ISSUE THREAD

**Issue by bittrex-bill** [aspnet/SignalR-Server#199]
Though this example is old, it shows a pattern of using a HubContext outside of a Hub class for broadcasting event based data.  http://www.asp.net/signalr/overview/getting-started/tutorial-server-broadcast-with-signalr  

Through the magic of Google, I stumbled upon http://stackoverflow.com/a/37776550/1693081.

Using this technique, I'm able to get a IHubContext which I assign as a static variable in the Startup class and in the debugger, an object is properly assigned.  Unfortunately, if I execute a command like: hub.Clients.All.SendMessage("foo") nothing is triggered on a connected client.  If I call the same client side command from within a hub and use the built in this.Clients.All.SendMessage, it works as expected.

Is this a bug or is there a different way I should get a hub context?

**Comment by IanYates** [comment]
I had this sort of grief in a small demo app I threw together once.  

It turns out I had 

    GlobalHost.DependencyResolver = new SignalRDependencyResolver(container);

and

    app.MapSignalR(new HubConfiguration()
                {
                    Resolver = new SignalRDependencyResolver(container)
                });


Getting rid of the second setting of "Resolver" fixed it.  Served me right for the quick & dirty nature of the demo.

**Comment by davidfowl** [comment]
Signalr core doesn't have any of this stuff. If this is about the non core signalr, the this is the wrong repository.

**Comment by bittrex-bill** [comment]
Hi David,

This is definitely about core.  

in startup.cs 

I declare a variable:
`public` static IServiceProvider ServiceProvider { get; private set; }`

in startup.cs ConfigureServices

`if (ServiceProvider  == null) ServiceProvider = services.BuildServiceProvider();`

Then in my class that serves data asynchronously to the sockets, I use: 

```
var connectionManager = Startup.ServiceProvider.GetService(typeof(IConnectionManager)) as IConnectionManager);
var context = connectionManager.GetHubContext<MyHub>();
context.Clients.SendMessage("Foo");  // does not send anything to connected clients
```

**Comment by davidfowl** [comment]
> I declare a variable:
public static IServiceProvider ServiceProvider { get; private set; }

Don't do that. Use dependency injection properly. Where is this class running? You can add it to the services collection then get an instance of it in Configure and boot up your background service that way:

```C#
public class Startup
{
   public void ConfigureServices(IServiceCollection services)
   {
        // Add services here
        services.AddSingleton<MyBackgroundService>();
   }

   public void Configure(IApplicationBuilder app, MyBackgroundService backgroundService)
   {
        backgroundService.Start();
        // Wire up middleware here
   }
}
```

```C#
public class MyBackgroundService
{
    private readonly IHubContext<MyHub> _hubContext;
    public MyBackgroundService(IHubContext<MyHub> hubContext)
    {
         _hubContext = hubContext;
    }

    public void Start()
    {
          // Send stuff to connected clients here
        _hubContext.Clients.SendMessage("Foo"); 
    }  
}
```
