### ISSUE TITLE
Error during WebSocket handshake: 'Sec-WebSocket-Accept' header is missing

### ISSUE THREAD

**Issue by DOMZE** [aspnet/SignalR-Server#201]
SignalR 3 user on ASP.NET 5 RC2

Getting the following error when trying to get websocket going.

Using Chrome 52.0.2743.116

Headers are the following:

**Request header:**
GET ws://host.tld/signalr/connect?transport=webSockets&clientProtocol=1.5&connectionToken=CfDJ8IAqJwUkPdtMulVy0xPQAAo2ZM%2FDEgWpxcvLiQNNXVmOKsPH%2BlqBdv9RPAG5DZGONZuHOPE2bhNozYE0V8gdjx599nIGw13RA38SozC5ETuRMSShRXRPaMurhABCQBSv1pGTEgs1C46Zd%2BsWHD%2BJvE6Y8bToqDQyY%2Bt6%2FLE5zz4w&connectionData=%5B%7B%22name%22%3A%22apphub%22%7D%5D&tid=6 HTTP/1.1
Host: host.tld
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: http://host.tld
Sec-WebSocket-Version: 13
DNT: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,fr;q=0.6
Cookie: *OMITTED*
Sec-WebSocket-Key: TrUaTnHL0KKcHxfc+sCDfA==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

**Response Header:**
HTTP/1.1 101 Switching Protocols
Transfer-Encoding: chunked
Upgrade: websocket
X-Content-Type-Options: nosniff
X-Powered-By: ASP.NET
Date: Tue, 09 Aug 2016 15:24:58 GMT

Microsoft.AspNetCore.WebSockets.Server: 0.1.0-rc2-final
Microsoft.AspNetCore.SignalR.Server: 0.1.0-*

Server Setup:
Windows Server 2012 R2
IIS 8.5

Anything I can do to get that fixed?

**Comment by moozzyk** [comment]
Running the sample from this repo I see this:

![image](https://cloud.githubusercontent.com/assets/1438884/17948370/79368d70-6a05-11e6-922b-2def0ca609de.png)

**Comment by DOMZE** [comment]
To those having the same issue, install WebSocket on IIS. solved my issue
