### ISSUE TITLE
Infinite NullReferenceException loop in HubRequestParser.Parse

### ISSUE THREAD

**Issue by yongyi781** [aspnet/SignalR-Server#202]
In recent dev builds of SignalR, using Kestrel + web sockets in a barebones SignalR application causes an infinite repeating wall of warning messages in the console when I press back on a page connected to a SignalR hub in Safari on iOS. The messages are all:

	warn: Microsoft.AspNetCore.SignalR.Transports.WebSocketTransport[0]
	      Exception thrown by Task
	System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
	   at Microsoft.AspNetCore.SignalR.Hubs.HubRequestParser.Parse(String data, JsonSerializer serializer)
	   at Microsoft.AspNetCore.SignalR.Hubs.HubDispatcher.OnReceived(HttpRequest request, String connectionId, String data)
	   at Microsoft.AspNetCore.SignalR.PersistentConnection.<>c__DisplayClass62_1.<ProcessRequestCore>b__5()
	   at Microsoft.AspNetCore.SignalR.TaskAsyncHelper.FromMethod(Func`1 func)
	   --- End of inner exception stack trace ---
	---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
	   at Microsoft.AspNetCore.SignalR.Hubs.HubRequestParser.Parse(String data, JsonSerializer serializer)
	   at Microsoft.AspNetCore.SignalR.Hubs.HubDispatcher.OnReceived(HttpRequest request, String connectionId, String data)
	   at Microsoft.AspNetCore.SignalR.PersistentConnection.<>c__DisplayClass62_1.<ProcessRequestCore>b__5()
	   at Microsoft.AspNetCore.SignalR.TaskAsyncHelper.FromMethod(Func`1 func)<---

This still happens in ASP.NET Core 1.1.0-alpha1-21900 (and SignalR 0.2.0-alpha1-21900). Using Kestrel, Web Sockets, and jQuery SignalR client 2.2.1.

**Comment by moozzyk** [comment]
Can you provide a repro?

**Comment by yongyi781** [comment]
It works with the absolute minimal SignalR application. Here's a concrete example nevertheless: https://github.com/yongyi781/signalr-bug-repro

**Comment by moozzyk** [comment]
I ran your repro on Mac and was able to see it once. Not sure what triggers the condition because I could not repro this again. Do you know how to repro this consistently?

**Comment by yongyi781** [comment]
Doesn't happen every time for me either; I don't know how to guarantee it happening :(
From what I tried it was quite likely to happen though. Did you run the server on a Mac too?

**Comment by moozzyk** [comment]
Yes. I converted the application to netcoreapp1.0 and ran it on a Mac.

**Comment by moozzyk** [comment]
It just happened to me and it seems that this call:
https://github.com/aspnet/SignalR-Server/blob/dev/src/Microsoft.AspNetCore.SignalR.Server/WebSockets/WebSocketHandler.cs#L161
completes immediately and returns the empty string as the data and as a result parsing this here: https://github.com/aspnet/SignalR-Server/blob/dev/src/Microsoft.AspNetCore.SignalR.Server/Hubs/HubRequestParser.cs#L21 returns null which causes the NRE. 
Note that this is not related to any specific browser or platform - we saw it happen now on all Windows, Mac and Linux.

**Comment by muratg** [comment]
Investigate

**Comment by anurse** [comment]
@moozzyk do you have a semi-reliable repro? I don't think I've seen it in my current WebSocketTransport testing.

**Comment by anurse** [comment]
Just saw the repro project above, I'll take a look at that as well.

**Comment by moozzyk** [comment]
When I tried it happened intermittently. @brecon said it happened each time he ran tests (on Mono :trollface:)

**Comment by anurse** [comment]
![https://giphy.com/gifs/l0HlBLtuZxMicyxzi](https://media.giphy.com/media/l0HlBLtuZxMicyxzi/giphy.gif)

(I kid ;P)

**Comment by anurse** [comment]
FYI it repros when running the app on Windows and using Safari on a macOS machine, so no iPhone is needed. I have a repro.

**Comment by moozzyk** [comment]
(I saw it happen when running the server on Windows and using Chrome)

**Comment by anurse** [comment]
Identified as an issue in aspnet/WebSockets, fix is in https://github.com/aspnet/WebSockets/pull/114 . Will close this when that gets merged.

**Comment by moozzyk** [comment]
The issue in WebSockets has been fixed so this one can be closed.
