### ISSUE TITLE
Implement compatibility test (SignalRCore server <--> SignalR 2.* clients)

### ISSUE THREAD

**Issue by muratg** [aspnet/SignalR-Server#206]
Implement infrastructure + bunch of initial tests. Should be able to use different clients.

Main planning issue: https://github.com/aspnet/SignalR-Server/issues/196

**Comment by anurse** [comment]
Matrix: C# Client, C++ Client, JS Client (in one browser)
Test Cases:
* [ ] Hubs
 * [ ] Connect to Server
 * [ ] Make RPC call (with return value)
 * [ ] Broadcast to all connected clients
 * [ ] Set ClientState on server, read on client
 * [ ] Join Group, Broadcast to Group
 * [ ] Join Group on Connection, Broadcast to Group
 * [ ] Kill transport mid session, test reconnect
* [ ] PersistentConnection
 * [ ] Connect to Server
 * [ ] Broadcast to all connected clients
 * [ ] Set ClientState on server, read on client
 * [ ] Join Group, Broadcast to Group
 * [ ] Join Group on Connection, Broadcast to Group
 * [ ] Kill transport mid session, test reconnect

**Comment by anurse** [comment]
JS tests got merged, right @moozzyk ?

**Comment by moozzyk** [comment]
Yeah but they are still flakey... (https://github.com/aspnet/SignalR-Server/issues/226). Fortunately I think I know why...

**Comment by anurse** [comment]
Cool, just checking in.
