### ISSUE TITLE
Implement async/await pattern throughout the code

### ISSUE THREAD

**Issue by muratg** [aspnet/SignalR-Server#212]
Now that we're targeting 4.5.2, we can finally do this.

See main 1.1 tracking issue: https://github.com/aspnet/SignalR-Server/issues/196#issuecomment-236242012

**Comment by grahamehorner** [comment]
SignalR & Reactive Extensions seem to have good alignment with regards to processing data streams (async) maybe SignalR client should have a Reactive Extension style Observable feel given that alignment & ReactiveJS  ;)

**Comment by davidfowl** [comment]
As an extension that would be fine, but I'd rather not tie the 2 together at the core.
