### ISSUE TITLE
abort returns http status code 200 and it should return 204

### ISSUE THREAD

**Issue by tahazayed** [aspnet/SignalR-Server#219]
This url '/signalr/abort' does not set a Content-Type header value. This value informs the browser what kind of data to expect. If this header is missing, the browser may incorrectly handle the data. This could lead to security problems.
while the response to /signalr/abort is always empty (i.e. there is no data to handle).

**Comment by moozzyk** [comment]
Can you elaborate on this: _ This could lead to security problems._

**Comment by tahazayed** [comment]
https://www.netsparker.com/web-vulnerability-scanner/vulnerability-security-checks-index/missing-content-type-header/

kindly follow the standard and set it to 204 as no content

**Comment by moozzyk** [comment]
I don't think it applies here since the response to the abort is empty but we will look into this.
