### ISSUE TITLE
SignalR relationship to WebSockets

### ISSUE THREAD

**Issue by radu-matei** [aspnet/SignalR-Server#220]
I've just created a very basic sample with SignalR Core and at first I missed the `app.UseWebSockets();` statement, which made the transport fall back.

What is (will be) the relationship between `Microsoft.AspNetCore.SignalR.Server` and `Microsoft.AspNet.Core.WebSockets`? Will I always have to add the socket support manually, or is it intended for SignalR to depend on it, making websocket connections possible without the additional line?

Thanks!

**Comment by davidfowl** [comment]
We haven't decided if we're always going to call it or not. Today you have to make 2 calls, but nothing is final.
