### ISSUE TITLE
Issues with ServerSentEvents and AspNetCoreModule in IIS Express

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR-Server#221]
We're seeing some issues with ANCM/IIS Express and ServerSentEvents. It seems to be getting in the way. This can be seen by running the JS SignalR 2.x Compat tests (Not yet checked-in, I'll update when it is) using a server behind ANCM.

Interestingly, this does not occur with the C# Client, so it may be something unique to the Browser EventSource client...?

Anyway, I hit this during my compat test work and didn't want to block on it so I'm filing this for tracking.

/cc @BrennanConroy @muratg @moozzyk

**Comment by moozzyk** [comment]
We hit this again when prototyping Sockets and IIS/ANCM seems to be the culprit so I opened https://github.com/aspnet/AspNetCoreModule/issues/16

**Comment by davidfowl** [comment]
This is resolved now right?

**Comment by muratg** [comment]
@Tratcher has a workaround in the bug @moozzyk linked.  Is that the way to go?

**Comment by Tratcher** [comment]
We have a few different options, we haven't settled on one yet. Start by making sure SignalR calls DisableResponseBuffering.

**Comment by davidfowl** [comment]
@Tratcher this version of SignalR already does that but since gzip compression actually works with SSE I'm not sure we want to call it all the time...

**Comment by Tratcher** [comment]
With the compression middleware you mean? DisableResponseBuffering only disables compression if Flush isn't supported

**Comment by davidfowl** [comment]
Ok, will do that then.
