### ISSUE TITLE
Compat Tests flakiness

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR-Server#226]
Compat tests fail sometimes due to a timeout. 

```
Microsoft.AspNetCore.SignalR.CompatTests.PersistentConnectionTests.Can_broadcast_to_groups(transportFactory: WebSock
etTransport) [FAIL]
      Receive timed out!
      Expected: True
      Actual:   False
```

Note that there are some ECONNRESET on the way:

```
      fail: Microsoft.AspNetCore.SignalR.Transports.WebSocketTransport[0]
info: Deployment[0]
            OnError(6b3ffcc6-0684-48c5-b296-1343b02000b1, System.Net.WebSockets.WebSocketException: The remote party clo
sed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: Error -4077 ECONNRESET
connection reset by peer ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4077 ECONNRESE
T connection reset by peer
info: Deployment[0]
```

Build log attached.

[build.log.txt](https://github.com/aspnet/SignalR-Server/files/465259/build.log.txt)

**Comment by HaoK** [comment]
Looks like there's another flakey one: http://aspnetci/project.html?projectId=XPlat&tab=testDetails&testNameId=6923342372492748820#analysis

**Comment by HaoK** [comment]
Muted the CompatJsTests.Run_javascript_compat_tests on CI for now

**Comment by moozzyk** [comment]
@HaoK  - thanks. I have a PR to disable these tests out for now (https://github.com/aspnet/SignalR-Server/pull/232).
