### ISSUE TITLE
Multiple Dependency Errors

### ISSUE THREAD

**Issue by GarySkills** [aspnet/SignalR-Server#227]
I tried to load this project in VS2015 Enterprise and I get 106 errors and it can't be built.  For example, here is one of them.  Is it something stupid i'm missing?

 
Error	CS0246	The type or namespace name 'ILoggerFactory' could not be found (are you missing a using directive or an assembly reference?)	Microsoft.AspNetCore.SignalR.Messaging..NET Framework 4.5.1	C:\SignalR-Server\src\Microsoft.AspNetCore.SignalR.Messaging\MessageBus.cs	27	Active

or this

NU1002 The dependency Microsoft.Extensions.Logging 1.1.0-alpha1-22119 in project Microsoft.AspNetCore.SignalR.Server does not support framework .NETFramework,Version=v4.5.1.

**Comment by BrennanConroy** [comment]
Go to Tools -> NuGet Package Manager -> Package Manager Console and type `dotnet --version`

**Comment by moozzyk** [comment]
Do you have VS 2015 Update 3 installed?

**Comment by GarySkills** [comment]
Yes, I have update 3 installed.

**Comment by GarySkills** [comment]
I did that and it says as follows

 

1.0.0-preview3-003592

**Comment by GarySkills** [comment]
I found a download for the .NET Core SDK Installer (Preview 2) and installed that and the issues got worse. Stating it could not find an executable for dotnet-projectmodel-server when i just opened the solution. Also received a few messages stating i should run dotnet restore for some lock file. I really don't know what this project needs to run properly. I am really interested in learning more about this for an upcoming project but i may have to wait for an official release or more info on how to get the solution to run. Is it supposed to run by just having Visual Studio Update 3 or do i need to load a few more things?

**Comment by BrennanConroy** [comment]
You should just need `VS U3` and `Microsoft .NET Core Tools (Preview 2)`

**Comment by BrennanConroy** [comment]
Have you looked at these instructions? https://www.microsoft.com/net/core#windows

**Comment by moozzyk** [comment]
I would also recommend cleaning NuGet cache by running `nuget.exe locals -clear all`

**Comment by moozzyk** [comment]
No follow up so I assume it is solved now.

**Comment by GarySkills** [comment]
Yes. Sorry I didn't follow up. I managed to get the project to run. However only a couple of the samples are working. I assume its a work in progress but thought I would ask if I should have expected all of the samples to work. For example, when I try the Drawing Pad or Real-time Broadcast samples, the screens are blank when I click on those buttons.

**Comment by moozzyk** [comment]
I do see that some samples show just a blank page. There seems to be some misconfiguration and the requests fail with an error similar to: "The request path /Hubs/DrawingPad/ does not match a supported file type".
