### ISSUE TITLE
Current Status

### ISSUE THREAD

**Issue by yehiasalam** [aspnet/SignalR-Server#231]
Hello,

I know that SignalR v3 is scheduled to be released in Q1/Q2 2017 according to your current roadmap but I'm starting a new project with ASP.net Core and it utilizes heavily WebSockets. My question is, will the 3.0.0 release on Jun 27 work in a production environment, I know it's a pre-release and can't really rely on it, however will the basic push/subscribe work as expected?

**Comment by moozzyk** [comment]
No, beta3 will not work with ASP.Net Core 1.*. However if you build the server on your own (dev branch) or use the nightly build package from the https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json feed things should work (again, pre-release quality).
