### ISSUE TITLE
SignalR http 503 when UWP app connecting (only release)

### ISSUE THREAD

**Issue by gsantopaolo** [aspnet/SignalR-Server#234]
I've a SignalR server deployed on a webapi role on Azure (Microsoft.AspNet.SignalR.Core, Version=2.2.1.0) and a uwp app (Microsoft.AspNet.SignalR.Client, Version=2.2.1.0) .
When client starts connection and only when the client is in release it got a 503 error from the server.
On the client I only see that the connection status changes to reconnecting, if i enable break on all exceptions i see Exception thrown: 'System.Exception' in System.Private.CoreLib.dll
Additional information: Service unavailable (503). (Excep_FromHResult 0x801901F7)
Server side, even if i'm logging everything, i can't trap the exception. i only see the 503 response from application insights.

Any suggestion?

thanks
-g

**Comment by davidfowl** [comment]
We're doing over the clients with SignalR Core, we can revisit then
