### ISSUE TITLE
Can I use it with ASP.NET Core using .NET Core not .NET Framework?

### ISSUE THREAD

**Issue by Jurabek** [aspnet/SignalR-Server#236]

**Comment by davidfowl** [comment]
Sure

**Comment by Jurabek** [comment]
Which nuget package should I install, I just using NET45 instead NetCoreApp1.0

**Comment by moozzyk** [comment]
If you want .NET Core target `netcoreapp1.0` as in this example: https://docs.asp.net/en/latest/getting-started.html. More in the docs: https://docs.asp.net/en/latest/
Closing as this is not a SignalR related issues.
