### ISSUE TITLE
Ubuntu (both 14 and 16) : Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl'

### ISSUE THREAD

**Issue by maiorfi** [aspnet/SignalR-Server#237]
Whenever I try to publish, upload and "dotnet <appname>.dll" a simple demo hub server application (named SignalRDemo.dll in stack trace below) or "dotnet restore" and "dotnet run" same application on Ubuntu 14 or 16 hosts, I always get following exception when first SignalR client tries to start a HubConnection:

```
Hosting environment: Production
Content root path: /home/netcoresamples/SignalRDemo/bin/Debug/netcoreapp1.0
Now listening on: http://*:8080
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://46.101.106.108:8080/signalr/hubs/signalr/negotiate?clientProtocol=1.4&connectionData=[%7B%22Name%22:%22updater%22%7D]
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HKVG3ILVJEFF": An unhandled exception was thrown by the application.
System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.Crypto.GetMaxMdSize()
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.GetRandomBytes(Byte[] buf, Int32 num)
   at System.Security.Cryptography.RNGCryptoServiceProvider.GetBytes(Byte[] data)
   at Microsoft.AspNetCore.SignalR.Infrastructure.SipHashBasedStringEqualityComparer.GenerateRandomKeySegment()
   at Microsoft.AspNetCore.SignalR.Messaging.TopicLookup..ctor()
   at Microsoft.AspNetCore.SignalR.Messaging.MessageBus..ctor(IStringMinifier stringMinifier, ILoggerFactory loggerFactory, IPerformanceCounterManager performanceCounterManager, IOptions`1 optionsAccessor)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.SignalR.PersistentConnection.Initialize(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.SignalR.Hosting.PersistentConnectionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 463.3489ms 200

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.SignalR.Messaging.MessageBus.GarbageCollectTopics()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

This is my NuGet.config:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <packageSources>
 <clear/>
 <add key="aspnetcidev" value="https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json"/>
 <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json"/>
 </packageSources>
</configuration>
```

This is my projects.json:
```
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.AspNetCore.Cors": "1.0.0",
    "Microsoft.AspNetCore.SignalR.Server": "0.2.0-*",
    "Microsoft.AspNetCore.WebSockets": "0.2.0-*",
    "System.Security.Cryptography.Algorithms": "4.3.0-preview1-24530-03"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

Any suggestions would be appreciated 😄 thanks

**Comment by moozzyk** [comment]
Do you have openssl installed on the machines you are trying to publish to?

**Comment by maiorfi** [comment]
Yes: 1.0.1 on Ubuntu14 and 1.0.2g on Ubuntu 16. Which version of OpenSSL libs do native crypto assembly "stubs" depend on?

**Comment by moozzyk** [comment]
I was able to repro this on my Ubuntu 14.04. I opened a bug in the corefx repo (https://github.com/dotnet/corefx/issues/12517) because it seems that it's not a missing dependency but the System.Security.Cryptography.Native.OpenSsl is nowhere to be found.

**Comment by halter73** [comment]
Change 

    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },

To this

    "Microsoft.NETCore.App": {
      "version": "1.1.0-*",
      "type": "platform"
    },

The problem is that `System.Security.Cryptography.Native.OpenSsl.so` doesn't exist in the 1.0.1 shared runtime, but it used (and is of course present) in the 1.1.0 shared runtime that SignalR-Server is currently built against. The two relevant directories look like this for me:

    shalter@debian82:~/$ cd ~/.dotnet/shared/Microsoft.NETCore.App/1.1.0-preview1-001090-00/
    shalter@debian82:~/.dotnet/shared/Microsoft.NETCore.App/1.1.0-preview1-001090-00$ ls
    Microsoft.CSharp.dll                     System.Diagnostics.Process.dll       System.Linq.Queryable.dll                System.Reflection.Emit.Lightweight.dll                 System.Security.Cryptography.Encoding.dll          System.Xml.ReaderWriter.dll
    Microsoft.CodeAnalysis.CSharp.dll        System.Diagnostics.StackTrace.dll    System.Linq.dll                          System.Reflection.Emit.dll                             System.Security.Cryptography.Native.OpenSsl.so     System.Xml.XDocument.dll
    Microsoft.CodeAnalysis.VisualBasic.dll   System.Diagnostics.Tools.dll         System.Native.a                          System.Reflection.Extensions.dll                       System.Security.Cryptography.OpenSsl.dll           System.Xml.XPath.XDocument.dll
    Microsoft.CodeAnalysis.dll               System.Diagnostics.Tracing.dll       System.Native.so                         System.Reflection.Metadata.dll                         System.Security.Cryptography.Primitives.dll        System.Xml.XPath.dll
    Microsoft.NETCore.App.deps.json          System.Dynamic.Runtime.dll           System.Net.Http.Native.so                System.Reflection.Primitives.dll                       System.Security.Cryptography.X509Certificates.dll  System.Xml.XmlDocument.dll
    Microsoft.VisualBasic.dll                System.Globalization.Calendars.dll   System.Net.Http.dll                      System.Reflection.TypeExtensions.dll                   System.Security.Principal.Windows.dll              corehost
    Microsoft.Win32.Primitives.dll           System.Globalization.Extensions.dll  System.Net.NameResolution.dll            System.Reflection.dll                                  System.Security.Principal.dll                      libclrjit.so
    Microsoft.Win32.Registry.dll             System.Globalization.Native.so       System.Net.Primitives.dll                System.Resources.Reader.dll                            System.Text.Encoding.CodePages.dll                 libcoreclr.so
    SOS.NETCore.dll                          System.Globalization.dll             System.Net.Requests.dll                  System.Resources.ResourceManager.dll                   System.Text.Encoding.Extensions.dll                libcoreclrtraceptprovider.so
    System.AppContext.dll                    System.IO.Compression.Native.so      System.Net.Security.Native.so            System.Runtime.Extensions.dll                          System.Text.Encoding.dll                           libdbgshim.so
    System.Buffers.dll                       System.IO.Compression.ZipFile.dll    System.Net.Security.dll                  System.Runtime.Handles.dll                             System.Text.RegularExpressions.dll                 libhostfxr.so
    System.Collections.Concurrent.dll        System.IO.Compression.dll            System.Net.Sockets.dll                   System.Runtime.InteropServices.RuntimeInformation.dll  System.Threading.Overlapped.dll                    libhostpolicy.so
    System.Collections.Immutable.dll         System.IO.FileSystem.Primitives.dll  System.Net.WebHeaderCollection.dll       System.Runtime.InteropServices.dll                     System.Threading.Tasks.Dataflow.dll                libmscordaccore.so
    System.Collections.dll                   System.IO.FileSystem.Watcher.dll     System.Numerics.Vectors.dll              System.Runtime.Loader.dll                              System.Threading.Tasks.Extensions.dll              libmscordbi.so
    System.ComponentModel.Annotations.dll    System.IO.FileSystem.dll             System.ObjectModel.dll                   System.Runtime.Numerics.dll                            System.Threading.Tasks.Parallel.dll                libsos.so
    System.ComponentModel.dll                System.IO.MemoryMappedFiles.dll      System.Private.CoreLib.dll               System.Runtime.dll                                     System.Threading.Tasks.dll                         libsosplugin.so
    System.Console.dll                       System.IO.UnmanagedMemoryStream.dll  System.Private.CoreLib.ni.dll            System.Security.Claims.dll                             System.Threading.Thread.dll                        libuv.so
    System.Diagnostics.Debug.dll             System.IO.dll                        System.Private.Uri.dll                   System.Security.Cryptography.Algorithms.dll            System.Threading.ThreadPool.dll                    mscorlib.dll
    System.Diagnostics.DiagnosticSource.dll  System.Linq.Expressions.dll          System.Reflection.DispatchProxy.dll      System.Security.Cryptography.Cng.dll                   System.Threading.Timer.dll                         mscorlib.ni.dll
    System.Diagnostics.FileVersionInfo.dll   System.Linq.Parallel.dll             System.Reflection.Emit.ILGeneration.dll  System.Security.Cryptography.Csp.dll                   System.Threading.dll                               sosdocsunix.txt

    shalter@debian82:~/.dotnet/shared/Microsoft.NETCore.App/1.1.0-preview1-001090-00$ cd ~/.dotnet/shared/Microsoft.NETCore.App/1.0.1/
    shalter@debian82:~/.dotnet/shared/Microsoft.NETCore.App/1.0.1$ ls
    Microsoft.CSharp.dll                     System.Diagnostics.StackTrace.dll    System.Linq.dll                          System.Reflection.Emit.dll                             System.Security.Cryptography.Native.so             System.Xml.XDocument.dll
    Microsoft.CodeAnalysis.CSharp.dll        System.Diagnostics.Tools.dll         System.Native.a                          System.Reflection.Extensions.dll                       System.Security.Cryptography.OpenSsl.dll           System.Xml.XPath.XDocument.dll
    Microsoft.CodeAnalysis.VisualBasic.dll   System.Diagnostics.Tracing.dll       System.Native.so                         System.Reflection.Metadata.dll                         System.Security.Cryptography.Primitives.dll        System.Xml.XPath.dll
    Microsoft.CodeAnalysis.dll               System.Dynamic.Runtime.dll           System.Net.Http.Native.so                System.Reflection.Primitives.dll                       System.Security.Cryptography.X509Certificates.dll  System.Xml.XmlDocument.dll
    Microsoft.NETCore.App.deps.json          System.Globalization.Calendars.dll   System.Net.Http.dll                      System.Reflection.TypeExtensions.dll                   System.Security.Principal.Windows.dll              corehost
    Microsoft.VisualBasic.dll                System.Globalization.Extensions.dll  System.Net.NameResolution.dll            System.Reflection.dll                                  System.Security.Principal.dll                      libclrjit.so
    Microsoft.Win32.Primitives.dll           System.Globalization.Native.so       System.Net.Primitives.dll                System.Resources.Reader.dll                            System.Text.Encoding.CodePages.dll                 libcoreclr.so
    Microsoft.Win32.Registry.dll             System.Globalization.dll             System.Net.Requests.dll                  System.Resources.ResourceManager.dll                   System.Text.Encoding.Extensions.dll                libcoreclrtraceptprovider.so
    System.AppContext.dll                    System.IO.Compression.Native.so      System.Net.Security.Native.so            System.Runtime.Extensions.dll                          System.Text.Encoding.dll                           libdbgshim.so
    System.Buffers.dll                       System.IO.Compression.ZipFile.dll    System.Net.Security.dll                  System.Runtime.Handles.dll                             System.Text.RegularExpressions.dll                 libhostfxr.so
    System.Collections.Concurrent.dll        System.IO.Compression.dll            System.Net.Sockets.dll                   System.Runtime.InteropServices.RuntimeInformation.dll  System.Threading.Overlapped.dll                    libhostpolicy.so
    System.Collections.Immutable.dll         System.IO.FileSystem.Primitives.dll  System.Net.WebHeaderCollection.dll       System.Runtime.InteropServices.dll                     System.Threading.Tasks.Dataflow.dll                libmscordaccore.so
    System.Collections.dll                   System.IO.FileSystem.Watcher.dll     System.Numerics.Vectors.dll              System.Runtime.Loader.dll                              System.Threading.Tasks.Extensions.dll              libmscordbi.so
    System.ComponentModel.Annotations.dll    System.IO.FileSystem.dll             System.ObjectModel.dll                   System.Runtime.Numerics.dll                            System.Threading.Tasks.Parallel.dll                libsos.so
    System.ComponentModel.dll                System.IO.MemoryMappedFiles.dll      System.Private.CoreLib.dll               System.Runtime.dll                                     System.Threading.Tasks.dll                         libsosplugin.so
    System.Console.dll                       System.IO.UnmanagedMemoryStream.dll  System.Private.CoreLib.ni.dll            System.Security.Claims.dll                             System.Threading.Thread.dll                        libuv.so
    System.Diagnostics.Debug.dll             System.IO.dll                        System.Private.Uri.dll                   System.Security.Cryptography.Algorithms.dll            System.Threading.ThreadPool.dll                    mscorlib.dll
    System.Diagnostics.DiagnosticSource.dll  System.Linq.Expressions.dll          System.Reflection.DispatchProxy.dll      System.Security.Cryptography.Cng.dll                   System.Threading.Timer.dll                         mscorlib.ni.dll
    System.Diagnostics.FileVersionInfo.dll   System.Linq.Parallel.dll             System.Reflection.Emit.ILGeneration.dll  System.Security.Cryptography.Csp.dll                   System.Threading.dll                               sosdocsunix.txt
    System.Diagnostics.Process.dll           System.Linq.Queryable.dll            System.Reflection.Emit.Lightweight.dll   System.Security.Cryptography.Encoding.dll              System.Xml.ReaderWriter.dll

@davidfowl @DamianEdwards @muratg @Eilon @pakrym   This was the exact same issue I was investigating last Friday. There are no restore or build errors, just this runtime error when you reference our newer packages but don't update the version of Microsoft.NETCore.App to 1.1.0.

I think that if this experience isn't fixed a lot of people will be left scratching their heads.

**Comment by halter73** [comment]
The fact that everything works on Windows then blows up at runtime on linux is particularly painful.

**Comment by maiorfi** [comment]
I'm trying to reference 1.1 netcore intead of 1.0.

Now my project.json is as follows:

```
{
  "dependencies": {
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0-*",
    "Microsoft.AspNetCore.SignalR.Server": "0.2.0-*",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0-*",
    "Microsoft.AspNetCore.WebSockets": "0.2.0-*",
    "Microsoft.Extensions.Logging.Console": "1.1.0-*",
    "Microsoft.AspNetCore.Cors": "1.1.0-*",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0-*"
  },
  "buildOptions": {
    "emitEntryPoint": true
  },
  "frameworks": {
    
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.1.0-*",
          "type": "platform"
        },
        "System.Runtime.Serialization.Primitives": "4.3.0-*"
      }
    }
  },
  "publishOptions": {
    "include": [
      "web.config"
    ]
  },
  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-*",
      "imports": "portable-net45+wp80+win8+wpa81+dnxcore50"
    }
  },
  "scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  }
}
```

I can do a successful "dotnet publish", but once deployed to a Ubuntu machine I get:

```
he specified framework 'Microsoft.NETCore.App', version '1.1.0-preview1-001100-00' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.0.1
  - Alternatively, install the framework version '1.1.0-preview1-001100-00'.
```

How should I update netcore frameowrk to version 1.1.0-* ?

Thanks!

**Comment by moozzyk** [comment]
You can try this: https://github.com/aspnet/DotNetTools/issues/139#issuecomment-253856633.

**Comment by halter73** [comment]
👍 Though obviously you would use the bash script in https://github.com/dotnet/cli/tree/rel/1.0.0/scripts/obtain instead of the powershell one.

**Comment by nbattaglia** [comment]
Hello maiorfi, could you deploy on linux server? I'm trying to do that on bluemix CF but i'm getting same error like you

**Comment by moozzyk** [comment]
1.1.0 is out and you can now use NuGet to get the dependencies.
