### ISSUE TITLE
SignalR Core server crashes on client connect (NullReferenceException)

### ISSUE THREAD

**Issue by Alexlander** [aspnet/SignalR-Server#238]
I've ported a SignalR mono server to run with SignalR Core on **Debian**, it runs correct on startup, but when a web or C# client joins it crashes with the following error:

> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.AspNetCore.SignalR.Messaging.MessageBus.GarbageCollectTopics()
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.TimerQueueTimer.CallCallback()
>    at System.Threading.TimerQueueTimer.Fire()
>    at System.Threading.TimerQueue.FireNextTimers()
> Aborted

And on the web-client it gives me: 500 Internal Error.

I just followed this tutorial https://radu-matei.github.io/blog/signalr-core/ , without changing my clients and hubs code.

I also use an Apache reverse proxy like this ProxyPass /signal http://localhost:5000

Any help/tips where to look are appreciated 😄

**Comment by davidfowl** [comment]
Just FYI, we're not shipping this version of SignalR so no work in actively happening on it.

**Comment by Alexlander** [comment]
Here is some "good news": 
I can connect a web-client fine when I host the SignalR Core server on Localhost, it is on Windows though.

I'll keep you guys updated.

**Comment by nbattaglia** [comment]
Hello Alexlander! I'm trying to do some like you in Bluemix with Ubuntu, and get same error. with netcore 1.0.1. have you gote some usefull results about this issue?

**Comment by Alexlander** [comment]
@nbattaglia Glad I wasn't the only one.. :) I hadn't found anything though, I just went over to the .Net Core 1.1.0 preview and it kinda worked, it should at least if you don't use an reverse proxy over a sub-domain.

Just try the preview out, I guess it was just a bug for Linux, things are still experimental right now.

**Comment by nbattaglia** [comment]
@Alexlander You are not the only one! It can be solved with 1.1.0 but meanwhile netcore netcore has no official sending that version, IBM implemented in bluemix not, then I can not try
