### ISSUE TITLE
renaming the hub causing [Hub could not be resolved] exception.

### ISSUE THREAD

**Issue by vivaunix** [aspnet/SignalR-Server#239]
I got a perfectly working hub named "alertHub". I renamed it to dataHub.
Here is what I got when I start the application:
2016-10-19 16:12:06.0582
Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1+<RequestProcessingAsync>d__2.MoveNext:
Connection id "0HKVOBDV2M7PT": An unhandled exception was thrown by the application.
System.InvalidOperationException 'alerthub' Hub could not be resolved. Microsoft.AspNetCore.SignalR.Hubs.HubDescriptor EnsureHub(Microsoft.AspNetCore.SignalR.Hubs.IHubManager, System.String, Microsoft.AspNetCore.SignalR.Infrastructure.IPerformanceCounter[])
ExecutionContext.Run => ExecutionContext.RunInternal => <RequestProcessingAsync>d__2.MoveNext

Application (WebAPI service) was running fine. The exception is being recorded by the logger.

dependencies:
"Microsoft.AspNetCore.Mvc": "1.0.1",
        "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
        "Microsoft.AspNetCore.SignalR.Server": "0.2.0-_",
        "Microsoft.AspNetCore.StaticFiles": "1.1.0-_",
        "Microsoft.AspNetCore.WebSockets": "0.2.0-*",
        "Microsoft.EntityFrameworkCore": "1.0.0",
        "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
        "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.0",
        "Microsoft.EntityFrameworkCore.Design": {
            "type": "build",
            "version": "1.0.0-preview2-final"
        },
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
        "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
        "Microsoft.Extensions.Configuration.Json": "1.0.0",
        "Microsoft.Extensions.Logging": "1.1.0-alpha1-22362",
        "Microsoft.Extensions.Logging.Console": "1.0.0",
        "Microsoft.Extensions.Logging.Debug": "1.0.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0"

Restarting the computer fixed the issue. (not Visual Studio 2015, but restarting the Windows 10).
Thank you!

**Comment by moozzyk** [comment]
Did you also fix this on the client side?

**Comment by halter73** [comment]
@moozzyk :+1:. My guess is that the old JS referencing "alertHub" was cached somewhere, and that the restart cleared the cache.

**Comment by vivaunix** [comment]
Yes, client side had been adjusted. By the way I had not started the client side. It happened right after starting the service. I am using WebAPI service to feed data to the Angular2 application. Angular is running via "npm start" that was down.
