### ISSUE TITLE
Package Restore Error : Microsoft.AspNetCore.SignalR.Server (>= 0.2.0)

### ISSUE THREAD

**Issue by tobiashoeft** [aspnet/SignalR-Server#240]
Hey Folks ,

my problem is the following , 

In my Asp.Net Core project 1.1.0-*

i would like to add SignalR 0.2.0-\* to my Project

`"Microsoft.AspNetCore.SignalR.Server": "0.2.0-*",
    "Microsoft.AspNetCore.WebSockets": "0.2.0-*",`

If i add this my dotnet restore failed because 

`Errors in D:****.Api\project.json

```
Unable to resolve 'Microsoft.Extensions.Logging.Console (>= 1.1.0)' for '.NETCoreApp,Version=v1.0'.

Unable to resolve 'Microsoft.Extensions.Logging.Debug (>= 1.1.0)' for '.NETCoreApp,Version=v1.0'`
```

And : 

`Unable to resolve 'runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography (>= 4.3.0-preview1-24530-04)' for '.NETCoreApp,Version=v1.0 (ubuntu.14.04-x64)'.`

I add the missing packages versions but it still dont work.

Any Idea? 

My deployment-target is .ubuntu.14.04-x64

My Project.json 👍 

`{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.1.0-_",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "MySql.Data.EntityFrameworkCore": "7.0.5-IR21",
    "MySql.Data.Core": "7.0.4-IR-191",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.SignalR.Server": "0.2.0-_",
    "Microsoft.AspNetCore.WebSockets": "0.2.0-*",
    "System.Security.Cryptography.Algorithms": "4.3.0-preview1-24530-03",
    "MimeKit": "1.8.0",
    "MailKit": "1.8.1",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "jose-jwt": "2.0.2",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },
  "runtimes": {
    "ubuntu.14.04-x64": {}
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "*_/_.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}`

Still Dependency problems and : 
 "Microsoft.AspNetCore.SignalR.Server": "0.2.0-_",
    "Microsoft.AspNetCore.WebSockets": "0.2.0-_",

could not resolved

**Comment by tobiashoeft** [comment]
Hi Murat , 

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="AspNetCore" value="https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json" />
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>`

**Comment by muratg** [comment]
Could you please try `aspnetcore-dev` instead of `aspnetcore-ci-dev`?   Packages in the "ci" feeds could be incoherent.

**Comment by tobiashoeft** [comment]
Same error : 
Errors in ****\*****.xproj
    Unable to resolve 'runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography (>= 4.3.0-preview1-24530-04)' for '.NETCoreApp,Version=v1.0 (ubuntu.14.04-x64)'.

**Comment by moozzyk** [comment]
I think there are some incompatibilities in this project - you pull some 1.0.0 versions of packages (e.g. "Microsoft.Extensions.Logging.Console": "1.0.0",) even though there are already 1.1.0 versions of the same packages available. Another is that you are going against 1.1.0 but you target netcoreapp1.0 instead of netcoreapp1.1.

**Comment by moozzyk** [comment]
Just to make it clear - all your dependencies need to be 1.1.0.
