### ISSUE TITLE
SignalR with aspnet core and full framework reference issue

### ISSUE THREAD

**Issue by dbus0** [aspnet/SignalR-Server#241]
I'm having trouble getting SignalR running with aspnet core and full framework. If I reference SignalR.Server 0.2.0-* I get runtime errors about assembly manifests not matching. I think I'm referencing the wrong build or wrong myget feed but am having trouble finding any information. Here are my configurations:

project.json:
```json
{
  "dependencies": {
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.SignalR.Server":  "0.2.0-*", 
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "net462": { }
  },
  ...
}
```

NuGet.config:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear/>
    <add key="aspnetcidev" value="https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json"/>
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json"/>
  </packageSources>
</configuration>
```

I spotted this in the output log:
```
warn : Detected package downgrade: Microsoft.Extensions.Logging from 1.1.0-preview2-22515 to 1.0.0 
warn :  ProjectName (>= 1.0.0) -> Microsoft.AspNetCore.SignalR.Server (>= 0.2.0) -> Microsoft.AspNetCore.SignalR.Messaging (>= 0.2.0-preview2-22515) -> Microsoft.Extensions.Logging (>= 1.1.0-preview2-22515) 
warn :  ProjectName (>= 1.0.0) -> Microsoft.Extensions.Logging (>= 1.0.0)
```

Runtime exception on startup:

> An unhandled exception of type 'System.IO.FileLoadException' occurred in Microsoft.AspNetCore.Hosting.dll
> 
> Additional information: Could not load file or assembly 'System.Diagnostics.Tracing, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by moozzyk** [comment]
SignalR packages are already targeting 1.1.0 packages and you are targeting 1.0.0 versions. Try changing versions to 1.1.0 for [these packages](https://github.com/aspnet/MetaPackages/blob/dev/src/Microsoft.AspNetCore/project.json)

**Comment by dbus0** [comment]
I've changed everything over to 1.1.0-* except for Microsoft.AspNetCore.Mvc which would only resolve 1.0.1 anyway. Still getting the runtime exception though. Was there any build of SignalR that targets the 1.0.1 release?

**Comment by moozzyk** [comment]
Microsoft.AspNetCore.Mvc should also be 1.1.0. I can see the package is there: https://dotnet.myget.org/feed/aspnetcore-ci-dev/package/nuget/Microsoft.AspNetCore.Mvc

**Comment by dbus0** [comment]
Hmm. I deleted out my packages folder and referenced Mvc 1.1.0-* successfully, but I'm still getting that exception. I've also added Autofac.Extensions.DependencyInjection.

Is there a build of SignalR for 1.0.1 anywhere? I would gladly just pull down the dll and reference it in my project if it were possible. Is anyone running SignalR on 1.0.1 as opposed to doing the preview builds?

**Comment by dbus0** [comment]
I ended up creating a blank solution in another folder and creating the project from scratch and got it working. Even though I tried creating the project from scratch within the previous solution to no avail. Lots of weird things in dotnet core like that.

**Comment by mathiasmarin** [comment]
Did you get signalR to work with a .Net Core (.Net framwework) web application? How? What was the necessary steps to make it work? Would realy apreciate your help! Thanks in advance!

**Comment by moozzyk** [comment]
@mathiasmarin - consider https://github.com/aspnet/SignalR-Server/blob/dev/README.md before investing too much time in trying this codebase.
