### ISSUE TITLE
0.2.0 Missing from Nuget?

### ISSUE THREAD

**Issue by mb2140** [aspnet/SignalR-Server#242]
Trying to pull from Nuget with 

PM> Install-Package Microsoft.AspNetCore.SignalR.Server -Version 0.2.0-preview2-22530

I get an error saying:

Retrieving package 'Microsoft.AspNetCore.SignalR.Server 0.2.0-preview2-22530' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.signalr.server/0.2.0-preview2-22530/microsoft.aspnetcore.signalr.server.0.2.0-preview2-22530.nupkg
  NotFound https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.signalr.server/0.2.0-preview2-22530/microsoft.aspnetcore.signalr.server.0.2.0-preview2-22530.nupkg 43ms
Install failed. Rolling back...

**Comment by moozzyk** [comment]
The core version of SignalR is not shipping on NuGet at the point as we still are prototyping how the core version will look like.
