### ISSUE TITLE
Consider renaming Microsoft.AspNetCore.SignalR.AuthorizeAttribute

### ISSUE THREAD

**Issue by mskurnik** [aspnet/SignalR-Server#247]
I was told I should post about this hear instead of [at the new repo](https://github.com/aspnet/SignalR/issues/42).

When calling a hub from a MVC controller that Authorize decorated on the class or method/view for example, there is an ambiguous reference between Microsoft.AspNetCore.SignalR.AuthorizeAttribute and Microsoft.AspNetCore.Authorization.AuthorizeAttribute. If you rename Microsoft.AspNetCore.SignalR.AuthorizeAttribute to Microsoft.AspNetCore.SignalR.Authentication.AuthorizeAttribute, you would remove this ambiguity.

**Comment by moozzyk** [comment]
As per https://github.com/aspnet/SignalR-Server/blob/6ddf4a2caced6a8e21c71d84bf8bdaef62b4f9f6/README.md we are not going to ship SignalR from this code. We are working on a new version which is not based on this code. Closing.
