### ISSUE TITLE
Port the functional tests over from SignalR/SignalR

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR-Server#31]

**Comment by muratg** [comment]
With @anurse's compat tests, this is partially done. We can extend that as we go.

**Comment by anurse** [comment]
FYI, my compat tests are **not** designed to be replacements for functional tests. They purely test the client-server protocol boundary features. There are deeper functional tests needed.

**Comment by moozzyk** [comment]
Agreed.
