### ISSUE TITLE
LongPolling start request returns InvalidOperationException: Incorrect Content-Type 

### ISSUE THREAD

**Issue by Xiaohongt** [aspnet/SignalR-Server#70]
SignalR server 3.0 returns InvalidOperationException: Incorrect Content-Type for longPolling start request with Content-Type: application/json; charset=UTF-8.

**Comment by borgdylan** [comment]
This happens on Kestrel for longPolling and server sent events as well.

**Comment by eduaglz** [comment]
I'm having the same issues but with SSE on a windows, Is getting the dev branch the only solution?

**Comment by DovydasNavickas** [comment]
With the beta5 build LongPolling start succeeds, poll requests succeed also. What still fails is send requests and they return same 500 error: Incorrect Content-Type.

**Comment by ChristopherHackett** [comment]
I am seeing the same thing attempting to run the SignelR sample in Beta8 release when I add in a Kestrel command. 

<img width="1164" alt="screen shot 2015-11-11 at 23 32 51" src="https://cloud.githubusercontent.com/assets/1075126/11106243/90105f0a-88cc-11e5-8084-2021825fb173.png">

**Comment by moozzyk** [comment]
This particular issue has been fixed. There is an issue with send requests that is being tracked in #91 and #111
