### ISSUE TITLE
SignalR .NET client 2.2.0 fails to invoke method on a SignalR Beta 3 server

### ISSUE THREAD

**Issue by Yves57** [aspnet/SignalR-Server#91]
When using a .NET client with SignalR 2.2.0 for .NET 4.5), the connection is successully started by it fails to invoke methods (generic error 500).
But to workaround the problem, I just have to downgrade the client SignalR version to 2.1.2 !
I use Windows 7 (so websockets are not used) and IIS Express.

Here the client code :
```
HubConnection hubConnection = new HubConnection("http://localhost:8187/");
var proxy = hubConnection.CreateHubProxy("PowerShellHub");
hubConnection.Start().Wait();
string s = hubConnection.Transport.Name; // 'serverSentEvents' is negociated
var res = proxy.Invoke<int>("Hello", 12).Result; // <-- Fail...
```

Here is the hub server code :
```
public class PowerShellHub : Hub
    {
		public PowerShellHub()
		{
		}
		public int Hello(int test)
		{
			return test * 2;
		}
    }
```

**Comment by rmja** [comment]
Could this be related to the discussion going on in #71?

**Comment by Yves57** [comment]
I have still the same problem with the Beta 4.
After debugging both Client (2.2.0) and Server, I found this issue:
- No problem during connection (my Hub constructor is called).
- The server fails during `ForeverTransport.ProcessSendRequest()` because `ReadFormAsync()` throw an exception (`HasFormContentType` is False).
- To fix the problem, I have added a ContentType in the `DefaultHttpClient` class:
```
public Task<IResponse> Post(string url, Action<IRequest> prepareRequest, IDictionary<string, string> postData, bool isLongRunning)
............
requestMessage.Content = new ByteArrayContent(HttpHelper.ProcessPostData(postData));
requestMessage.Content.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/x-www-form-urlencoded");
...........
```
I have a very simple sample ready if some additional tests are necessary.

**Comment by staff0rd** [comment]
I took a look at [this](https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Core/Transports/ForeverTransport.cs) and I can't tell how it used to figure out that the data wasn't being form-encoded.

Anyhow, f713ec6 is a fix for it until someone knowledgeable points out what is missing.

**Comment by rmja** [comment]
@staff0rd, the problem exists for the other transports as well - at least for LongPollingTransport. If you plan to send a pr, make sure that these are fixed as well.

**Comment by staff0rd** [comment]
I'm questioning whether the problem existed in the v2 server as well.  If it didn't, then this is likely a hacky work-around than a fix...

**Comment by ZoolWay** [comment]
Hello! Having the same issue with SignalR .NET client `2.2.0` connecting to SignalR server `3.0.0-rc1-final`, transport is `serverSentEvents`

**Comment by MoiraG** [comment]
Me too. SignalR .NET client 2.2. and SignalR server 3.0.0-rc1-final

**Comment by davidfowl** [comment]
SignalR isn;t being worked on until we ship v1.0. You won't see any activity until we get the first release out.
