### ISSUE TITLE
Don't use JsonSerializer to serialize/deserialize the container

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR-Server#99]
The container should be read and written using JsonReader/JsonWriter for performance and so any serializer settings, like modifying property names using CamelCasePropertyNameResolver, don't effect the way the container is serialized.

**Comment by georgiosd** [comment]
Not just that but if you replace JsonSerializer in the ServiceProvider, SignalR will stop working, presumably because in some places the serializer is created, not injected (try Find all usages for JsonSerializer with R#)

**Comment by muratg** [comment]
In SignalR Core, this won't be relevant any more per the new design.  We're not going to have hardcoded framing. 

You will be able to specify different formatters -- for an example, see https://github.com/davidfowl/Sockets/blob/master/samples/SocketsSample/Startup.cs#L49-L51
